import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { ChainInfo } from '@/lib/keplr'

const inter = Inter({ subsets: ['latin'] })

const noisConfig: ChainInfo = {
	"chainId": "nois-testnet-003",
	"chainName": "Nois Testnet",
	"rpc": "https://rpc.nois.mcbnode.online",
	"rest": "https://api.nois.mcbnode.online",
	"bip44": {
    coinType: 118
  },
	"bech32Config": {
		"bech32PrefixAccAddr": "nois",
		"bech32PrefixAccPub": "noispub",
		"bech32PrefixValAddr": "noisvaloper",
		"bech32PrefixValPub": "noisvaloperpub",
		"bech32PrefixConsAddr": "noisvalcons",
		"bech32PrefixConsPub": "noisvalconspub"
	},
	"currencies": [
		{
			"coinDenom": "NOIS",
			"coinMinimalDenom": "unois",
			"coinDecimals": 6,
			"coinGeckoId": "unknown"
		}
	],
	"feeCurrencies": [
		{
			"coinDenom": "NOIS",
			"coinMinimalDenom": "unois",
			"coinDecimals": 6,
			"coinGeckoId": "unknown",
      gasPriceStep: {
        "low": 0.05,
        "average": 0.05,
        "high": 0.1
      }
		}
	],
	"stakeCurrency": {
		"coinDenom": "NOIS",
		"coinMinimalDenom": "unois",
		"coinDecimals": 6,
		"coinGeckoId": "unknown"
	},
	"features": []
}

function addNoisAsSuggestedChain() {
  console.log("Do it!")
  const anyWindow: any = window;
  if (!anyWindow.keplr) {
    alert("Keplr not found")
  } else {
    anyWindow.keplr.experimentalSuggestChain(noisConfig);
  }
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <button onClick={() => addNoisAsSuggestedChain()}>Add Nois Testnet to Keplr</button>
        </div>

        <div className={styles.grid}>
          <a
            href="https://docs.nois.network"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              All about Nois
            </p>
          </a>

          <a
            href="https://chat.nois.network"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Chat <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Get help and meet the community
            </p>
          </a>

          <a
            href="https://whitepaper.nois.network"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Whitepaper <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              The whitepaper.
            </p>
          </a>

          <a
            href="https://twitter.com/NoisNetwork"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Twitter <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Follow Nois on Twitter to get the latest news about the project.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
