import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { noisConfig } from "@/lib/noisConfig";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [lastError, setLastError] = useState<string>();

  function addNoisAsSuggestedChain() {
    setLastError(undefined);
    const anyWindow: any = window;
    if (!anyWindow.keplr) {
      alert("Keplr not found");
      setLastError("Keplr not found");
    } else {
      anyWindow.keplr.experimentalSuggestChain(noisConfig).then(
        () => console.log("Suggested chain installed"),
        (err: any) => {
          console.error(err);
          setLastError("An error occurred when adding the suggested chain");
        },
      );
    }
  }

  return (
    <>
      <Head>
        <title>Nois Address Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <p>
            <button onClick={() => addNoisAsSuggestedChain()}>Add Nois Testnet to Keplr</button>
          </p>

          {lastError && <p>{lastError}</p>}
        </div>

        <div className={styles.grid}>
          <a
            href="https://docs.nois.network"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>All about Nois</p>
          </a>

          <a
            href="https://chat.nois.network"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Chat <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Get help and meet the community</p>
          </a>

          <a
            href="https://whitepaper.nois.network"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Whitepaper <span>-&gt;</span>
            </h2>
            <p className={inter.className}>The whitepaper.</p>
          </a>

          <a
            href="https://twitter.com/NoisNetwork"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Twitter <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Follow Nois on Twitter to get the latest news about the project.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
